# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                ("repo", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                (
                    "sha",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("img", models.BinaryField()),
            ],
        )
    ]
